db:
  image: mongo
  ports:
    - "27017:27017"
  command: "--smallfiles --logpath=/dev/null"
api:
  build: https://github.com/alairjt/CrawlerNodeAPI.git
  command: npm start
  volumes:
    - .:/crawlernodeapi
  ports:
    - "5000:5000"
  links:
    - db
web:
  build: https://github.com/alairjt/CrawlerNodeWeb.git
  volumes:
      - '/usr/src/app'
      - '/usr/src/app/node_modules'
  ports:
    - "3000:3000"
